name: build2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PACKAGES_ENABLED_FOR_CLANG_UNIX: -d tl-expected/ -d tl-expected-tests/ -d tl-optional/ -d tl-optional-tests/

jobs:

  # Job for building on Ubuntu
  Ubuntu:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - name: Ubuntu gcc Debug
            os: ubuntu-latest
            config_file: gcc.debug.build
            packages: --all

          - name: Ubuntu gcc Release
            os: ubuntu-latest
            config_file: gcc.release.build
            packages: --all

          - name: Ubuntu clang Debug
            os: ubuntu-latest
            config_file: clang.debug.build
            packages: $PACKAGES_ENABLED_FOR_CLANG_UNIX

          - name: Ubuntu clang Release
            os: ubuntu-latest
            config_file: clang.release.build
            packages: $PACKAGES_ENABLED_FOR_CLANG_UNIX

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: build2/setup-build2-github-action@v2
        with:
          build2-version: staged
      - name: Install dependencies
        run: sudo apt-get update
      - name: Configure
        run: |
              bdep init --empty
              bdep config create @cc  ../build-tl cc config.config.load=build-config/${{matrix.config.config_file}}
              bdep init ${{matrix.config.packages}}
      - name: Build
        run: bdep update -V
      - name: Tests
        run: bdep test -V

  # Job for building on MacOS
  MacOS:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - name: MacOS clang Debug
            os: macos-latest
            config_file: clang.debug.build

          - name: MacOS clang Release
            os: macos-latest
            config_file: clang.release.build

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: build2/setup-build2-github-action@v2
      with:
        build2-version: staged
    - name: Configure
      run: |
            bdep init --empty
            bdep config create @cc  ../build-tl cc config.config.load=build-config/${{matrix.config.config_file}}
            bdep init $PACKAGES_ENABLED_FOR_CLANG_UNIX
    - name: Build
      run: bdep update -V
    - name: Tests
      run: bdep test -V

  # Job for building on Windows
  Windows:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
            - name: Windows msvc Debug
              os: windows-latest
              config_file: msvc.debug.build
              compiler_type: msvc

            - name: Windows msvc Release
              os: windows-latest
              config_file: msvc.release.build
              compiler_type: msvc

            - name: Windows clang Debug
              os: windows-latest
              config_file: clang.debug.build
              compiler_type: clang

            - name: Windows clang Release
              os: windows-latest
              config_file: clang.release.build
              compiler_type: clang

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: build2/setup-build2-github-action@v2
      with:
        build2-version: staged
        build2-windows-compiler: ${{matrix.config.compiler_type}}
    - name: Configure
      run: bdep init -C  ../build-tl @cc cc config.config.load=build-config/${{matrix.config.config_file}}
    - name: Build
      run: bdep update -V
    - name: Tests
      run: bdep test -V
